services:
  server:
    build: ./server
    container_name: openvpn-server
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    sysctls:
      - net.ipv4.ip_forward=1
    ports:
      - "1194-1195:1194-1195/udp"
    restart: unless-stopped
    volumes:
      - ./networks:/etc/openvpn/networks:ro
      - server-log:/var/log
    networks:
      vpn-net:
        ipv4_address: 172.20.0.2
  client:
    build: ./client
    depends_on: 
      - server
    container_name: openvpn-client
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      CLIENT_NAME: client1
      NETWORKS: example-tap
    restart: unless-stopped
    volumes:
      - ./networks:/etc/openvpn/networks:ro
      - server-log:/var/log
    networks:
      vpn-net:
        ipv4_address: 172.20.0.5

volumes:
  server-log:

networks:
  vpn-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
